<?php echo $this->doctype(); ?>


<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('ZF2 PHP-DI TEST')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <?php echo $this->headLink(array(
                            'rel' => 'shortcut icon', 
                            'type' => 'image/vnd.microsoft.icon', 
                            'href' => $this->basePath() . '/favicon.ico'))
                        ->prependStylesheet($this->basePath('/style.css'))
        ?>

        <?php echo $this->headScript()
            ->prependFile($this->basePath('functions.js'))
         ?>

    </head>
    <body>
    <div style='background: yellow; padding:10px; margin:5px;'>
        TEST SITE LAYOUT HEADER
        <br clear="all">
    </div>
    <div style='background: #efefef; padding:10px; margin:5px;'>
        <?php echo $this->content; ?>
    </div>

    <?php echo $this->inlineScript() ?>
    
    </body>
</html>
